config/routes.rb
Rails.application.routes.draw do

  get "agents/index"

  root "home#index"
  get '/home' => 'home#default_homepage'
  

  devise_for :users, controllers: {
    registrations: 'users/registrations',
    omniauth_callbacks: 'users/omniauth_callbacks'
  }
    resources :users do
      member do
        get :statistics_data
        patch :approve
        patch :reject
        get :reviews
        get :review_events
        patch :mark_email_sent
      end
      collection do
        get :all_users
        get :managerealtors
      end
  end

  get "agents", to: "agents#index", as: :agents

  resources :dev_projects do
    get '/page/:page', action: :index, on: :collection
    member do
      get :statistics_data
      delete :remove_attachment
    end
  end

  resources :model_houses do 
    member do
      delete :remove_attachment
    end
  end

  resources :realtor_signup, only: [:index, :new, :create] do
    collection do
      get :search_brokers
      get :search_realties
      get :search_broker_prc_no
    end
  end

  get 'thank_you_realtor', to: 'realtor_signup#thank_you_realtor'


  resources :listings do
    resources :reviews, only: [:new, :create, :destroy]
    get '/page/:page', action: :index, on: :collection
    post 'contact_agent', on: :member

    member do
      get :statistics_data
      post :confirm
      patch :reverse_confirm
      get 'public'
      delete :remove_attachment
    end
  end
  get  '/select_type', to: 'listings#select_type'
  post '/choose_type', to: 'listings#choose_type', as: :choose_type_listings
  get  '/new_independent', to: 'listings#new_independent'
  get  '/new_project', to: 'listings#new_project'
  get '/public_listings', to: 'listings#public_listings'


  resources :conversations, only: [:index, :show, :new, :create] do
    resources :messages, only: [:create]
  end

  get "notifications/unread_count", to: "notifications#unread_count"

  namespace :admin do
  resources :users, only: [:new, :create, :update] do
    member do
        patch :reset_password
    end
  end
      
  resources :listings, only: [:index, :show, :destroy] do
    member do
      patch :approve
      patch :reject
    end
    collection do
      get :metadata_search
    end
  end

  resources :realties, only: [:index, :show, :destroy] do
    member do
      patch :approve
      patch :reject 
    end
  end

  resources :rebap_memberships, only: [:index, :new, :create]

  resources :password_reset_logs, only: [:index]
end

  resources :guides do
    collection do
      get :my_guides
    end
    resources :comments, only: [:create]
  end

  resources :saved_listings, only: [:index, :create, :destroy]

  get "notifications/unread_count", to: "notifications#unread_count"

  resources :review_events, only: [] do
    member do
      patch :mark_as_read
    end
  end

 resources :realties do
  resources :realty_memberships, only: [:create, :update, :destroy] do
    member do
      patch :approve
      patch :reject
      patch :request_removal
      patch :approve_removal
      patch :reject_removal
      patch :force_remove
    end
  end

  resources :accreditations, only: [:create]

  member do
      get :edit_requirements
      patch :update_requirements
      get :manage_members
    end
  end

  resources :accreditations, only: [:update, :destroy] do
    collection do
      get :developer_requests
    end
  end

  resources :rebaps, only: [:show, :edit, :update] do
    collection do
      get :manage_members
      post :add_member
      delete :remove_member
      get :manage_officers
      patch :assign_officer
      delete :unassign_officer
    end
  end

  get "search", to: "search#index"

  resources :transactions, only: [:index]


  mount Importmap::Engine => "/rails/importmap"
  # mount ActionCable.server => '/cable'

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
end

app/views/shared/_admin_dashboard.html.erb
<div class="ml-1 mb-3">
  <h1>Welcome back</h1>
  <h2><%= current_user.first_name %></h2>
</div>

<div class="d-flex flex-wrap gap-1">
  <%= link_to "Manage Users", all_users_users_path, class: "btn btn-light" %>
  <%= link_to "Approve Realtors", managerealtors_users_path, class: "btn btn-light" %>
  <%= link_to "Approve Listings", admin_listings_path, class: "btn btn-light" %>
  <%= link_to "Manage Realties", admin_realties_path, class: "btn btn-light" %>
  <%= link_to "Manage REBAP", admin_rebap_memberships_path, class: "btn btn-light" %>
  <%= link_to "Transactions", transactions_path, class: "btn btn-light" %>
  <%= link_to "Create New User", new_admin_user_path, class: "btn btn-info" %>
</div>

app/views/shared/_amenities.html.erb
<div class="container mt-2 mb-2 bg-light">
  <div class="p-3">
    <h5>Amenities</h5>
    <% if property.amenities.any? %>
      <% groups = property.amenities.map do |a|
           (image_tag(a.icon, size: "20x20") + " " + a.label).html_safe
         end.in_groups(3, false) %>

      <div class="row">
        <% groups.each do |group| %>
          <div class="col-md-4 small">
            <% group.each do |amen_html| %>
              <p><%= amen_html %></p>
            <% end %>
          </div>
        <% end %>
      </div>
    <% else %>
      No amenities available.
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<!-- Footer -->
<div class="footer-container">
  <footer class="text-center text-lg-start bg-body-tertiary text-muted">
    <!-- Section: Social media -->
    <section class="d-flex justify-content-center justify-content-lg-between p-4 border-bottom">
      <!-- Left -->
      <div class="me-5 d-none d-lg-block">
        <span>Get connected with us on social networks:</span>
      </div>
      <!-- Left -->

      <!-- Right -->
      <div>
        <a href="https://www.facebook.com/" class="me-4 text-reset" target="_blank">
          <i class="bi bi-facebook"></i>
        </a>
        <a href="https://x.com/" class="me-4 text-reset" target="_blank">
          <i class="bi bi-twitter"></i>
        </a>
        <a href="https://www.instagram.com/" class="me-4 text-reset" target="_blank">
          <i class="bi bi-instagram"></i>
        </a>
        <a href="https://www.linkedin.com/" class="me-4 text-reset" target="_blank">
          <i class="bi bi-linkedin"></i>
        </a>
      </div>
      <!-- Right -->
    </section>
    <!-- Section: Social media -->

    <!-- Section: Links  -->
    <section class="">
      <div class="container text-center text-md-start mt-5">
        <!-- Grid row -->
        <div class="row mt-3">
          <!-- Grid column -->
          <div class="col-md-3 col-lg-4 col-xl-3 mx-auto mb-4">
            <!-- Content -->
            <h6 class="fw-bold mb-4">
              <%= image_tag "favicon-96x96", alt: "Bahayahy-Logo", size: "30x30", class: "me-1"  %>
              <%= image_tag "rebap-favicon", alt: "REBAP-Naga Logo", size: "30x30" %>
              <i class="fas fa-gem me-2"></i>Bahayahay x REBAP Naga
            </h6>
            <p>
              Developed in partnership with REBAP Naga City Chapter—ensuring you only deal with legit agents while finding your home.
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-3 col-lg-2 col-xl-2 mx-auto mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">
              Useful links
            </h6>
            <p>
              <a href="#!" class="text-reset">About Us</a>
            </p>
            <p>
              <a href="#!" class="text-reset">FAQs</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Terms & Conditions</a>
            </p>
            <p>
              <a href="#!" class="text-reset">Privacy Policy</a>
            </p>
          </div>
          <!-- Grid column -->

          <!-- Grid column -->
          <div class="col-md-4 col-lg-3 col-xl-3 mx-auto mb-md-0 mb-4">
            <!-- Links -->
            <h6 class="text-uppercase fw-bold mb-4">Contact</h6>
            <p><i class="fas fa-home me-3"></i> Naga City, Camarines Sur 4400 PH</p>
            <p>
              <i class="fas fa-envelope me-3"></i>
              bahayahay.ph@gmail.com
            </p>
            <p><i class="fas fa-phone me-3"></i> + 63 947 252 2888</p>
          </div>
          <!-- Grid column -->
        </div>
        <!-- Grid row -->
      </div>
    </section>
    <!-- Section: Links  -->
  </footer>
  <!-- Footer -->

app/views/shared/_navbar.html.erb
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light p-2">
  <%= link_to root_path, class: "navbar-brand d-flex align-items-center" do %>
    <%= image_tag "favicon-96x96", alt: "Bahayahay Logo", size: "30x30", class: "me-1" %>
    <div class="nav-item logo-name">Bahayahay</div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <% if user_signed_in? %>
      <% if current_user.admin? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/home">Website Home</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/public_listings">Live Listings</a>
          </li>
        </ul>

        <ul class="navbar-nav ml-auto">
          <%= form_with url: search_path, method: :get, local: true, class: "d-flex my-3 my-lg-0" do %>
            <%= text_field_tag :q, params[:q], placeholder: "Search site-wide", class: "form-control me-2" %>
            <button class="btn btn-outline-success btn-sm me-2" type="submit">Search</button>
          <% end %>

          <li class="nav-item active">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class:"nav-link" %>
          </li>
        </ul>

      <% elsif current_user.developer? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/dev_projects">Your Projects</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/model_houses">Your Model Houses</a>
          </li>
          <li class="nav-item mt-1 dropdown">
            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Post New
            </button>
            <ul class="dropdown-menu">
              <%= link_to "Development Project", new_dev_project_path, class: "dropdown-item" %>
              <%= link_to "Model House", new_model_house_path, class: "dropdown-item" %>
            </ul>
          </li>
        </ul>

        <% elsif current_user.rebap? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/public_listings">Explore Homes</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/guides/new">Create a Guide</a>
          </li>
          <li class="nav-item mt-1 dropdown">
            <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown"
              aria-haspopup="true" aria-expanded="false">
              Manage
            </button>
            <ul class="dropdown-menu">
              <%= link_to "Officers", manage_officers_rebaps_path, class: "dropdown-item" %>
              <%= link_to "Active Members", manage_members_rebaps_path, class: "dropdown-item" %>
            </ul>
          </li>
        </ul>


      <% elsif current_user.realtor? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/public_listings">Explore Homes</a>
          </li>
          <li class="nav-item active">
            <a class="nav-link" href="/listings">Your Listings</a>
          </li>
          </li>
          <li class="nav-item active">
            <% if current_user&.is_broker? %>
              <% if current_user.managed_realty&.persisted? %>
                <%= link_to "Your Realty", realty_path(current_user.managed_realty), class: "nav-link" %>
              <% else %>
                <%= link_to "Apply to Create a Realty", new_realty_path, class: "nav-link" %>
              <% end %>
            <% end %> 
          </li>
          <% if current_user.realtor? && (current_user.is_broker || current_user.approved_realty.present?) %>
            <li class="nav-item active mt-1">
              <a href="/select_type" class="btn btn-secondary btn-sm" role="button">New Listing</a>
            </li>
          <% end %>
        </ul>

      <% elsif current_user.client? %>
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/public_listings">Explore Homes</a>
          </li>
        </ul>
      <% end %>
    <% else %>
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="/public_listings">Explore Homes</a>
        </li>
        <li class="nav-item active">
          <a class="nav-link" href="/agents">Find an Agent</a>
        </li>
        <li class="nav-item active">
          <%= link_to "Sign up as a Realtor", new_realtor_signup_path, class:"nav-link", data: { turbo: false } %>
        </li>
      </ul>
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <%= link_to "Log In", new_user_session_path, class:"nav-link" %>
        </li>
        <li class="nav-item active">
          <a href="/users/sign_up" class="btn btn-success me-2 my-2 my-lg-0" role="button">Sign up</a>
        </li>
      </ul>
    <% end %>

    <!-- Right side if signed-in -->
    <% if user_signed_in? && !current_user.admin? %>
      <ul class="navbar-nav ml-lg-auto d-flex flex-column flex-lg-row justify-content-start justify-content-lg-end align-items-start align-items-lg-center">

        <%= form_with url: search_path, method: :get, local: true, class: "d-flex my-3 my-lg-0" do %>
          <%= text_field_tag :q, params[:q], placeholder: "Search site-wide", class: "form-control me-2" %>
          <button class="btn btn-outline-success btn-sm me-2" type="submit">Search</button>
        <% end %>

        <% if current_user.realtor? %>
          <li class="nav-item active mx-2 position-relative">
            <a class="btn btn-light position-relative" href="<%= reviews_user_path(current_user) %>">
              <i class="bi bi-chat-left-quote-fill"></i>
            </a>
          </li>
        <% end %>
        <% if !current_user.client? %>
          <li class="nav-item active mx-2">
            <a class="btn btn-light" href="/guides/my_guides">
              <i class="bi bi-pencil"></i>
            </a>
          </li>
        <% end %>
        <% if current_user.client? || current_user.realtor? %>
          <li class="nav-item active mx-2 position-relative">
            <a class="btn btn-light position-relative" href="/conversations">
              <i class="bi bi-send-fill"></i>
          <!-- <span id="inbox-badge"
                class="position-absolute top-0 start-100 translate-middle badge rounded-pill bg-danger d-none px-1 py-0"
                style="font-size: 0.75rem; transform: translate(-50%, -30%);">
                0
              </span> -->
            </a>
          </li>
        <% end %>
        <% if current_user.client? %>
          <li class="nav-item active mx-2">
            <a class="btn btn-light" href="/saved_listings">
              <i class="bi bi-floppy2-fill"></i>
            </a>
          </li>

           <li class="nav-item active mx-2 position-relative">
            <a class="btn btn-light position-relative" href="<%= review_events_user_path(current_user) %>">
              <i class="bi bi-chat-left-quote-fill"></i>
            </a>
          </li>
        <% end %>
        <% if current_user.developer? %>
          <li class="nav-item active mx-2 position-relative">
            <a class="btn btn-light position-relative" href="<%= developer_requests_accreditations_path %>">
              <i class="bi bi-arrow-bar-down"></i>
            </a>
          </li>
        <% end %>
        <li class="nav-item mx-2 dropdown">
          <button type="button" class="btn btn-light dropdown-toggle" data-bs-toggle="dropdown"
            aria-haspopup="true" aria-expanded="false">
            <i class="bi bi-person-circle"></i>
          </button>
          <ul class="dropdown-menu dropdown-menu-end">
            <%= link_to "My Profile", user_path(current_user), class: "dropdown-item" %>
            <%= link_to "Account Settings", edit_user_registration_path, class: "dropdown-item" %>
            <div class="dropdown-divider"></div>
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </ul>
        </li>
      </ul>
    <% end %>
  </div>
</nav>